---
services:
  frontend:
    #image: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_frontend_AMD_1
    platform: linux/amd64
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    #image: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_backend_AMD_1
    platform: linux/amd64
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
