services:
  - type: web
    name: restriction-digest-app
    plan: free
    runtime: image
    image:
      url: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_app_AMD_1
    envVars:
      - key: PORT
        value: 3000
