services:
  - type: web
    name: frontend
    plan: free
    runtime: image
    image:
      url: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_frontend_AMD_1

  - type: web 
    name: backend
    plan: free
    runtime: image
    image:
      url: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_backend_AMD_1
    envVars:
      - key: PORT
        value: 3001
