services:
  - type: web
    name: frontend
    runtime: image
    image:
      url: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_frontend_1

  - type: web 
    name: backend
    runtime: image
    image:
      url: mpampuch/restriction-enzyme-digest-tool:restriction-enzyme-digest-tool_backend_1
    envVars:
      - key: PORT
        value: 3001
